name: Compile RP2040 Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install ARM GCC Compiler and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake

    - name: Setup Pico SDK
      uses: frenck/action-setup-pico-sdk@v1
      with:
        version: '1.5.1'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ../workflow

    - name: Build Project
      run: |
        cd build
        make -j$(nproc)

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rp2040-uf2-binaries
        path: |
          build/*.uf2
          build/*.elf
          build/*.bin
